Reward fund account implementation
BluedDot-IT/laravel-unit-sdk pull request #3
Opened 2023-06-21 09:51 UTC by tanerincode

2023-06-27 11:30 UTC, Physicliar approved these changes

2023-06-27 11:30 UTC, Physicliar commented on src/Services/RewardService.php
> +    public function createReward(array $data, string $processType = 'depositAccount'): RewardServiceInterface {
instead we should select type I think we should just get the funding account id as optional as second parameter and if funding account parameter exists we add id to the body. So we will not change the existing structure and will add optional parameter which will keep us safe.

2023-06-27 11:33 UTC, Physicliar requested changes

2023-06-27 11:33 UTC, Physicliar commented on src/Services/RewardService.php
> +    public function createReward(array $data, string $processType = 'depositAccount'): RewardServiceInterface {
Requested changes

2023-07-03 08:13 UTC, tanerincode commented on src/Services/RewardService.php
> +    public function createReward(array $data, string $processType = 'depositAccount'): RewardServiceInterface {
updated

2023-07-03 09:22 UTC, Physicliar requested changes

2023-07-03 09:22 UTC, Physicliar commented on src/Services/RewardService.php
> +                    "type" => 'fundingAccount',
it should be also depositAccount not funding account and can you please double quote

2023-07-03 09:30 UTC, Physicliar approved these changes

2023-07-03 09:31 UTC, merged

2023-07-03 09:37 UTC, tanerincode commented on src/Services/RewardService.php
> +                    "type" => 'fundingAccount',
done